development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: 
  pool: 5
  username: 
  password: 
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: 
  pool: 5
  username: 
  password: 
  host: localhost
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: 
  pool: 5
  username: 
  password: 
  host: localhost
